MYNEDATA_DIR="/opt/mynedata"
MYNEDATA_LOGDIR="/opt/mynedata/log"

MYNEDATA_FRONTEND_DIR="${MYNEDATA_DIR}/frontend"
MYNEDATA_FRONTEND_BUILD="${MYNEDATA_DIR}/frontend_build"

MYNEDATA_BITCOIN_DIR="${MYNEDATA_DIR}/bitcoin"
MYNEDATA_BITCOIN_CONFIG="${MYNEDATA_BITCOIN_DIR}/bitcoin.conf"
MYNEDATA_BITCOIN_DATADIR="${MYNEDATA_BITCOIN_DIR}/datadir"
MYNEDATA_BITCOIND="${MYNEDATA_BITCOIN_DIR}/bin/bitcoind"
MYNEDATA_BITCOINCLI="${MYNEDATA_BITCOIN_DIR}/bin/bitcoin-cli"
MYNEDATA_BITCOIN_STDPARAMS="-conf=${MYNEDATA_BITCOIN_CONFIG} -datadir=${MYNEDATA_BITCOIN_DATADIR} -regtest"

WEBSERVER_DIR="/etc/nginx"
WEBSERVER_CONFIG="${WEBSERVER_DIR}/nginx.conf"

NPM_CONFIG_PREFIX="${MYNEDATA_DIR}/npm"
