#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    MY_DIR="$(readlink -f ${0} | xargs dirname)"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    MY_DIR="$(greadlink -f ${0} | xargs dirname)"
fi

# clean build folder (sphinx)
pushd "${MY_DIR}/../doc"
make clean

# remove autogenerated module files (sphinx)
pushd "source"
find . -type f ! -name "index.rst" ! -name "conf.py" -exec rm {} \;
popd

# creates module files (swaggerdoc)
rm api/index.html
popd
